### ISSUE TITLE
Export Directory

### ISSUE THREAD

**Issue by Squiblydoo** [knight0x07/OneNoteAnalyzer#1]
Greetings,
I may make a pull request for this later.

Can I suggest making a directory in the current working directory with the name of the file you are dumping and put the contents in there?

With the current configuration, there is no clean way to analyze multiple documents as all the contents will be dropped to the folders in the hard drive’s root directory in the new folders it creates.

**Comment by knight0x07** [comment]
Yo Squiblydoo!

Thanks! Your suggestion is appreciated. I'll take care of this and quickly update the code with the export directory =)

Regards,
knight0x07

**Comment by knight0x07** [comment]
Hello! I updated the code - Creates an Export Directory with the OneNote Document filename and dumps all the extracted data in that directory itself. The compiled binary can be downloaded from *Releases*.

![export_1](https://user-images.githubusercontent.com/60843949/213372797-e74d76d5-d4d1-4f74-8a54-06c3364ffe62.PNG)

Do let me know if you come across any issues!

Regards,
knight0x07

**Comment by Squiblydoo** [comment]
Awesome. Thank you. :)
